/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthApi,
  AutoMLServiceApi,
  ClientApi,
  EnrichedTransactionsApi,
  HealthApi,
  PersonasApi,
  StatisticsApi,
  UsersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { HyperplaneCustom } from "./client-custom";

export class Hyperplane extends HyperplaneCustom {
  readonly auth: AuthApi;
  readonly autoMLService: AutoMLServiceApi;
  readonly client: ClientApi;
  readonly enrichedTransactions: EnrichedTransactionsApi;
  readonly health: HealthApi;
  readonly personas: PersonasApi;
  readonly statistics: StatisticsApi;
  readonly users: UsersApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.auth = new AuthApi(configuration);
    this.autoMLService = new AutoMLServiceApi(configuration);
    this.client = new ClientApi(configuration);
    this.enrichedTransactions = new EnrichedTransactionsApi(configuration);
    this.health = new HealthApi(configuration);
    this.personas = new PersonasApi(configuration);
    this.statistics = new StatisticsApi(configuration);
    this.users = new UsersApi(configuration);
  }

}
