/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsPersonaCreateResponse
 */
export interface ModelsPersonaCreateResponse {
    /**
     * Creation datetime of persona
     * @type {string}
     * @memberof ModelsPersonaCreateResponse
     */
    'creation_datetime': string;
    /**
     * Unique identifier for the persona
     * @type {string}
     * @memberof ModelsPersonaCreateResponse
     */
    'persona_id': string;
    /**
     * Name of the persona
     * @type {string}
     * @memberof ModelsPersonaCreateResponse
     */
    'persona_name': string;
}

