/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPersonaScorePercentiles } from './models-persona-score-percentiles';

/**
 * Statistical attributes about the score distribution for a particular persona.
 * @export
 * @interface ModelsPersonaScoreStatistics
 */
export interface ModelsPersonaScoreStatistics {
    /**
     * Highest persona score assigned to a user for this persona
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'maximum_user_score': number;
    /**
     * Lowest persona score assigned to a user for this persona
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'minimum_user_score': number;
    /**
     * Score threshold used to determine whether a user belongs to this persona
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'persona_score_threshold': number;
    /**
     * Average score over all scored users in this persona
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'score_average': number;
    /**
     * Percentile distribution of scores for users who have been assigned a score for this persona
     * @type {ModelsPersonaScorePercentiles}
     * @memberof ModelsPersonaScoreStatistics
     */
    'score_percentiles': ModelsPersonaScorePercentiles;
    /**
     * Standard deviation over all scored users in this persona
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'score_standard_deviation': number;
    /**
     * Total number of users who meet or exceed the score threshold to be considered part of this persona.
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'total_users_above_threshold': number;
    /**
     * Total number of users who have received a score for this persona.
     * @type {number}
     * @memberof ModelsPersonaScoreStatistics
     */
    'total_users_with_non_zero_score': number;
}

