/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsInputLabelSummary
 */
export interface ModelsInputLabelSummary {
    /**
     * Counts of given labels, broken down by label and weight. The keys are stringified pairs of (label_value, weight_value).
     * @type {{ [key: string]: number; }}
     * @memberof ModelsInputLabelSummary
     */
    'label_weight_counts'?: { [key: string]: number; };
    /**
     * For each month (shown in YYYY-MM format), the number of labels given.
     * @type {{ [key: string]: number; }}
     * @memberof ModelsInputLabelSummary
     */
    'monthly_counts'?: { [key: string]: number; };
    /**
     * For each month (shown in YYYY-MM format), what is the rate of positive labels given.
     * @type {{ [key: string]: number; }}
     * @memberof ModelsInputLabelSummary
     */
    'monthly_positive_rates'?: { [key: string]: number; };
    /**
     * Number of labels that were provided by the user.
     * @type {number}
     * @memberof ModelsInputLabelSummary
     */
    'num_input_labels': number;
    /**
     * Number of distinct users that were provided by the user
     * @type {number}
     * @memberof ModelsInputLabelSummary
     */
    'num_input_users': number;
    /**
     * Number of data rows that will be used in training
     * @type {number}
     * @memberof ModelsInputLabelSummary
     */
    'num_matched_labels': number;
    /**
     * Number of distinct users that will be used in training
     * @type {number}
     * @memberof ModelsInputLabelSummary
     */
    'num_training_users': number;
}

