/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Inflow and outflow for a given user in a given time window
 * @export
 * @interface ModelsCashflowWindowStatistics
 */
export interface ModelsCashflowWindowStatistics {
    /**
     * Inflow amount on the given window
     * @type {number}
     * @memberof ModelsCashflowWindowStatistics
     */
    'inflow_amount'?: number;
    /**
     * Outflow amount on the given window
     * @type {number}
     * @memberof ModelsCashflowWindowStatistics
     */
    'outflow_amount'?: number;
    /**
     * End time of the given window
     * @type {string}
     * @memberof ModelsCashflowWindowStatistics
     */
    'window_end'?: string;
    /**
     * Start time of the given window
     * @type {string}
     * @memberof ModelsCashflowWindowStatistics
     */
    'window_start'?: string;
}

