/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsLookalikeLabel } from './models-lookalike-label';

/**
 * 
 * @export
 * @interface ModelsAutoMLLookalikeCreateRequest
 */
export interface ModelsAutoMLLookalikeCreateRequest {
    /**
     * Intended use case of this product, between MULTI_ENGAGE and SINGLE_ENGAGE
     * @type {string}
     * @memberof ModelsAutoMLLookalikeCreateRequest
     */
    'engagement_type': string;
    /**
     * List of negative users in lookalike model. Model will be trained to identify users dissimilar to these users. If None, negative users will be generated from data. List length must be either 0 or greater than 10.
     * @type {Array<ModelsLookalikeLabel>}
     * @memberof ModelsAutoMLLookalikeCreateRequest
     */
    'negative_label_users'?: Array<ModelsLookalikeLabel>;
    /**
     * List of positive users in lookalike model. Model will be trained to identify users similar to these users. This list must contain at least ten elements.
     * @type {Array<ModelsLookalikeLabel>}
     * @memberof ModelsAutoMLLookalikeCreateRequest
     */
    'positive_label_users': Array<ModelsLookalikeLabel>;
    /**
     * Custom run description to attach to run
     * @type {string}
     * @memberof ModelsAutoMLLookalikeCreateRequest
     */
    'run_description'?: string;
}

