/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPersonaCreateRequest } from './models-persona-create-request';
import { ModelsPersonaScoreStatistics } from './models-persona-score-statistics';

/**
 * 
 * @export
 * @interface ModelsPersonaDetailsResponse
 */
export interface ModelsPersonaDetailsResponse {
    /**
     * Creation datetime of persona
     * @type {string}
     * @memberof ModelsPersonaDetailsResponse
     */
    'creation_datetime': string;
    /**
     * The persona definition used to create this persona
     * @type {ModelsPersonaCreateRequest}
     * @memberof ModelsPersonaDetailsResponse
     */
    'definition': ModelsPersonaCreateRequest;
    /**
     * Unique identifier for the persona
     * @type {string}
     * @memberof ModelsPersonaDetailsResponse
     */
    'persona_id': string;
    /**
     * Statistical attributes about the persona score distribution
     * @type {ModelsPersonaScoreStatistics}
     * @memberof ModelsPersonaDetailsResponse
     */
    'persona_score_statistics': ModelsPersonaScoreStatistics;
}

