/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsBatchUserPersonasRequest
 */
export interface ModelsBatchUserPersonasRequest {
    /**
     * All user ids we want to fetch personas for
     * @type {Array<string>}
     * @memberof ModelsBatchUserPersonasRequest
     */
    'user_ids': Array<string>;
}

