/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Definition of a filter on an attribute of numerical type.
 * @export
 * @interface ModelsNumericalAttributeFilter
 */
export interface ModelsNumericalAttributeFilter {
    /**
     * Max attribute value
     * @type {number}
     * @memberof ModelsNumericalAttributeFilter
     */
    'max_value': number;
    /**
     * Min attribute value
     * @type {number}
     * @memberof ModelsNumericalAttributeFilter
     */
    'min_value': number;
}

