/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Transaction statistics for a given user
 * @export
 * @interface ModelsUserTransactionsStatisticsResponse
 */
export interface ModelsUserTransactionsStatisticsResponse {
    /**
     * Average transaction value
     * @type {number}
     * @memberof ModelsUserTransactionsStatisticsResponse
     */
    'average_transaction_value'?: number;
    /**
     * Median transaction value
     * @type {number}
     * @memberof ModelsUserTransactionsStatisticsResponse
     */
    'median_transaction_value'?: number;
    /**
     * Number of transactions
     * @type {number}
     * @memberof ModelsUserTransactionsStatisticsResponse
     */
    'transaction_count': number;
}

