/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * General statistics for a given transaction enrichment module
 * @export
 * @interface ModelsTransactionEnrichmentStatisticsResponse
 */
export interface ModelsTransactionEnrichmentStatisticsResponse {
    /**
     * Number of transactions in the module
     * @type {number}
     * @memberof ModelsTransactionEnrichmentStatisticsResponse
     */
    'transaction_count': number;
    /**
     * Number of distinct users in the module
     * @type {number}
     * @memberof ModelsTransactionEnrichmentStatisticsResponse
     */
    'user_reach': number;
}

