/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsAutoMLRunMetrics
 */
export interface ModelsAutoMLRunMetrics {
    /**
     * Cumulative positive rates at various thresholds, including ascending (lower to higher thresholds) and descending (higher to lower thresholds). It indicates how the proportion of positive instances within the total instances changes as the classification threshold is adjusted.
     * @type {{ [key: string]: { [key: string]: number; }; }}
     * @memberof ModelsAutoMLRunMetrics
     */
    'cumulative_positive_rate'?: { [key: string]: { [key: string]: number; }; };
    /**
     * The percentage of users with positive label in the test set.
     * @type {number}
     * @memberof ModelsAutoMLRunMetrics
     */
    'label_positive_rate'?: number;
    /**
     * The percentage of positive examples (examples with a positive label) in each of the ten equally-sized groups (deciles) of the test data when this data is sorted based on the model\'s predicted scores.
     * @type {{ [key: string]: number; }}
     * @memberof ModelsAutoMLRunMetrics
     */
    'positive_rate_by_decile'?: { [key: string]: number; };
    /**
     * AUC of the test set
     * @type {number}
     * @memberof ModelsAutoMLRunMetrics
     */
    'test_auc'?: number;
    /**
     * KS of the test set
     * @type {number}
     * @memberof ModelsAutoMLRunMetrics
     */
    'test_ks'?: number;
    /**
     * AUC of the training set
     * @type {number}
     * @memberof ModelsAutoMLRunMetrics
     */
    'train_auc'?: number;
    /**
     * KS of the training set
     * @type {number}
     * @memberof ModelsAutoMLRunMetrics
     */
    'train_ks'?: number;
}

