/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Location where the transaction happened
 * @export
 * @interface ModelsLocation
 */
export interface ModelsLocation {
    /**
     * City name
     * @type {string}
     * @memberof ModelsLocation
     */
    'city'?: string;
    /**
     * IBGE city code
     * @type {string}
     * @memberof ModelsLocation
     */
    'city_code'?: string;
    /**
     * Country name
     * @type {string}
     * @memberof ModelsLocation
     */
    'country'?: string;
    /**
     * Full address (e.g., Av. Lúcio Costa 1234, Copacabana, Rio de Janeiro, Brasil)
     * @type {string}
     * @memberof ModelsLocation
     */
    'full_address'?: string;
    /**
     * Location latitude
     * @type {number}
     * @memberof ModelsLocation
     */
    'latitude'?: number;
    /**
     * Location longitude
     * @type {number}
     * @memberof ModelsLocation
     */
    'longitude'?: number;
    /**
     * Postal code (i.e., CEP, e.g., \'22620-171\')
     * @type {string}
     * @memberof ModelsLocation
     */
    'postal_code'?: string;
    /**
     * Primary address (e.g., Av. Lúcio Costa, 1234)
     * @type {string}
     * @memberof ModelsLocation
     */
    'primary_address'?: string;
    /**
     * State name
     * @type {string}
     * @memberof ModelsLocation
     */
    'state'?: string;
    /**
     * Type of location (e.g., personal, home, business, ...)
     * @type {string}
     * @memberof ModelsLocation
     */
    'type'?: string;
}

