/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPersonaUser } from './models-persona-user';

/**
 * Response of users linked to a given persona
 * @export
 * @interface ModelsPersonaUsersResponse
 */
export interface ModelsPersonaUsersResponse {
    /**
     * Top users belonging to this persona
     * @type {Array<ModelsPersonaUser>}
     * @memberof ModelsPersonaUsersResponse
     */
    'users': Array<ModelsPersonaUser>;
}

