/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsUserScore
 */
export interface ModelsUserScore {
    /**
     * Model inference score for the user
     * @type {number}
     * @memberof ModelsUserScore
     */
    'score': number;
    /**
     * UserID is the unique identifier for the user
     * @type {string}
     * @memberof ModelsUserScore
     */
    'user_id': string;
}

