/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Percentile scores for users scored for a particular persona.
 * @export
 * @interface ModelsPersonaScorePercentiles
 */
export interface ModelsPersonaScorePercentiles {
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_10'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_20'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_30'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_40'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_50'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_60'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_70'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_80'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPersonaScorePercentiles
     */
    'percentile_90'?: number;
}

