/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * User associated with a given persona
 * @export
 * @interface ModelsUserPersonaScore
 */
export interface ModelsUserPersonaScore {
    /**
     * Unique identifier for the persona
     * @type {string}
     * @memberof ModelsUserPersonaScore
     */
    'persona_id': string;
    /**
     * Name of the persona
     * @type {string}
     * @memberof ModelsUserPersonaScore
     */
    'persona_name': string;
    /**
     * Relevance score of user in this persona. In range `[0,1]`
     * @type {number}
     * @memberof ModelsUserPersonaScore
     */
    'persona_score'?: number;
}

