/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsCategoryCashflow } from './models-category-cashflow';

/**
 * Amount percentage for a given top level category. As well as subcategories division
 * @export
 * @interface ModelsTopLevelCategoryCashflow
 */
export interface ModelsTopLevelCategoryCashflow {
    /**
     * Aggregate amount for the given category
     * @type {number}
     * @memberof ModelsTopLevelCategoryCashflow
     */
    'amount'?: number;
    /**
     * Detailed predicted categories under the top-level
     * @type {Array<ModelsCategoryCashflow>}
     * @memberof ModelsTopLevelCategoryCashflow
     */
    'categories'?: Array<ModelsCategoryCashflow>;
    /**
     * Human-friendly category name
     * @type {string}
     * @memberof ModelsTopLevelCategoryCashflow
     */
    'name'?: string;
    /**
     * Absolute amount flow for the category
     * @type {number}
     * @memberof ModelsTopLevelCategoryCashflow
     */
    'percentage'?: number;
}

