/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsClientResponse
 */
export interface ModelsClientResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsClientResponse
     */
    'access_key_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsClientResponse
     */
    'is_disabled'?: boolean;
}

