/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsFacetWeightObject
 */
export interface ModelsFacetWeightObject {
    /**
     * Name of the facet
     * @type {string}
     * @memberof ModelsFacetWeightObject
     */
    'name': string;
    /**
     * Weight of the facet
     * @type {number}
     * @memberof ModelsFacetWeightObject
     */
    'weight': number;
}

