/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Inferred merchant info after transaction enrichment
 * @export
 * @interface ModelsMerchantInfo
 */
export interface ModelsMerchantInfo {
    /**
     * Merchant business name
     * @type {string}
     * @memberof ModelsMerchantInfo
     */
    'business_name'?: string;
    /**
     * Merchant category
     * @type {string}
     * @memberof ModelsMerchantInfo
     */
    'category'?: string;
    /**
     * Merchant CNAE
     * @type {string}
     * @memberof ModelsMerchantInfo
     */
    'cnae'?: string;
    /**
     * Merchant CNPJ
     * @type {string}
     * @memberof ModelsMerchantInfo
     */
    'cnpj'?: string;
    /**
     * Merchant name
     * @type {string}
     * @memberof ModelsMerchantInfo
     */
    'name'?: string;
}

