/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Percentile and associated score.
 * @export
 * @interface ModelsPercentileScore
 */
export interface ModelsPercentileScore {
    /**
     * Percentile for which the score is being fetched
     * @type {number}
     * @memberof ModelsPercentileScore
     */
    'percentile'?: number;
    /**
     * Score calculated for the given percentile
     * @type {number}
     * @memberof ModelsPercentileScore
     */
    'score'?: number;
}

