/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Definition of a filter on an attribute of timestamp type.
 * @export
 * @interface ModelsTimestampAttributeFilter
 */
export interface ModelsTimestampAttributeFilter {
    /**
     * Max attribute value
     * @type {string}
     * @memberof ModelsTimestampAttributeFilter
     */
    'max_value': string;
    /**
     * Min attribute value
     * @type {string}
     * @memberof ModelsTimestampAttributeFilter
     */
    'min_value': string;
}

