/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsUserMetadata
 */
export interface ModelsUserMetadata {
    /**
     * UserID is the unique identifier for the user
     * @type {string}
     * @memberof ModelsUserMetadata
     */
    'user_id': string;
}

