/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsUserMetadata } from './models-user-metadata';

/**
 * 
 * @export
 * @interface ModelsAutoMLUsersGetResponse
 */
export interface ModelsAutoMLUsersGetResponse {
    /**
     * List of users\' metadata
     * @type {Array<ModelsUserMetadata>}
     * @memberof ModelsAutoMLUsersGetResponse
     */
    'user_list': Array<ModelsUserMetadata>;
}

