/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsTransferParty } from './models-transfer-party';

/**
 * Metadata related to the money transfer and involved parties
 * @export
 * @interface ModelsTransferMetadata
 */
export interface ModelsTransferMetadata {
    /**
     * Transfer payment method
     * @type {string}
     * @memberof ModelsTransferMetadata
     */
    'payment_method'?: string;
    /**
     * Transfer inferred reason
     * @type {string}
     * @memberof ModelsTransferMetadata
     */
    'reason'?: string;
    /**
     * Transfer party that receives the money
     * @type {ModelsTransferParty}
     * @memberof ModelsTransferMetadata
     */
    'receiver'?: ModelsTransferParty;
    /**
     * Transfer reference number
     * @type {string}
     * @memberof ModelsTransferMetadata
     */
    'reference_number'?: string;
    /**
     * Transfer party that sends the money
     * @type {ModelsTransferParty}
     * @memberof ModelsTransferMetadata
     */
    'sender'?: ModelsTransferParty;
}

