/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsTransactionEnrichmentUser
 */
export interface ModelsTransactionEnrichmentUser {
    /**
     * Date for first transaction registered for a given user.
     * @type {string}
     * @memberof ModelsTransactionEnrichmentUser
     */
    'first_transaction_date': string;
    /**
     * Date for last transaction registered for a given user.
     * @type {string}
     * @memberof ModelsTransactionEnrichmentUser
     */
    'last_transaction_date': string;
    /**
     * Unique user identifier
     * @type {string}
     * @memberof ModelsTransactionEnrichmentUser
     */
    'user_id': string;
}

