/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Attributes related to the sender or receiver of a given transaction
 * @export
 * @interface ModelsTransferParty
 */
export interface ModelsTransferParty {
    /**
     * Party account number
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'account_number'?: string;
    /**
     * Party branch number
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'branch_number'?: string;
    /**
     * Party document name
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'document_name'?: string;
    /**
     * Party document number
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'document_number'?: string;
    /**
     * Party name
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'name'?: string;
    /**
     * Party routing number
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'routing_number'?: string;
    /**
     * Party ISPB routing number
     * @type {string}
     * @memberof ModelsTransferParty
     */
    'routing_number_ISPB'?: string;
}

