/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsPaginationMetadata
 */
export interface ModelsPaginationMetadata {
    /**
     * Next page number
     * @type {number}
     * @memberof ModelsPaginationMetadata
     */
    'next_page': number;
    /**
     * Number of elements per page
     * @type {number}
     * @memberof ModelsPaginationMetadata
     */
    'page_size': number;
}

