/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsAutoMLRunSummary } from './models-auto-mlrun-summary';

/**
 * 
 * @export
 * @interface ModelsAutoMLRunsGetResponse
 */
export interface ModelsAutoMLRunsGetResponse {
    /**
     * List of AutoML run summaries
     * @type {Array<ModelsAutoMLRunSummary>}
     * @memberof ModelsAutoMLRunsGetResponse
     */
    'runs': Array<ModelsAutoMLRunSummary>;
}

