/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPersonaCreateResponse } from './models-persona-create-response';

/**
 * Response of users linked to a given persona
 * @export
 * @interface ModelsListPersonasResponse
 */
export interface ModelsListPersonasResponse {
    /**
     * 
     * @type {Array<ModelsPersonaCreateResponse>}
     * @memberof ModelsListPersonasResponse
     */
    'personas': Array<ModelsPersonaCreateResponse>;
}

