/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsTopLevelCategoryCashflow } from './models-top-level-category-cashflow';

/**
 * 
 * @export
 * @interface ModelsUserCashflowPerCategoryResponse
 */
export interface ModelsUserCashflowPerCategoryResponse {
    /**
     * Inflow discriminated by category
     * @type {Array<ModelsTopLevelCategoryCashflow>}
     * @memberof ModelsUserCashflowPerCategoryResponse
     */
    'inflow_categories'?: Array<ModelsTopLevelCategoryCashflow>;
    /**
     * Outflow discriminated by category
     * @type {Array<ModelsTopLevelCategoryCashflow>}
     * @memberof ModelsUserCashflowPerCategoryResponse
     */
    'outflow_categories'?: Array<ModelsTopLevelCategoryCashflow>;
    /**
     * User identifier
     * @type {string}
     * @memberof ModelsUserCashflowPerCategoryResponse
     */
    'user_id'?: string;
}

