/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsFacetWeightObject } from './models-facet-weight-object';

/**
 * Defines a persona. Stores various weighted facets including their interests, demographics, location, company affinity, as well as predefined personas.
 * @export
 * @interface ModelsPersonaCreateRequest
 */
export interface ModelsPersonaCreateRequest {
    /**
     * Optional list of behavioral facet component objects. Each object outlines how a user\'s likelihood to consume from a particular company\'s products and how much it contributes to the persona definition. If left empty, no company-based scoring is done. Company facets can be found by listing personas of facet type \'company\'. Facet name must be a valid company facet in the persona taxonomy.
     * @type {Array<ModelsFacetWeightObject>}
     * @memberof ModelsPersonaCreateRequest
     */
    'company_facets'?: Array<ModelsFacetWeightObject>;
    /**
     * Optional list of interest facet component objects. Defines how much each demographic attribute (location, affluence, household composition, etc.)  weighs in the persona. If left empty, no demographic-based scoring is done. Demographic facets can be found by listing personas of facet type \'demographic\'. Facet name must be a valid demographic facet in the persona taxonomy.
     * @type {Array<ModelsFacetWeightObject>}
     * @memberof ModelsPersonaCreateRequest
     */
    'demographic_facets'?: Array<ModelsFacetWeightObject>;
    /**
     * Optional list of interest facet component objects. Each object represents how much an interest weighs in the persona. If left empty, no interest-based scoring is done. Interests can be found by listing personas of facet type \'interest\'. Facet name must be a valid interest in the persona taxonomy.
     * @type {Array<ModelsFacetWeightObject>}
     * @memberof ModelsPersonaCreateRequest
     */
    'interest_facets'?: Array<ModelsFacetWeightObject>;
    /**
     * Optional list of zip codes or city ids to filter users by. If left empty, no location-based filtering is done.
     * @type {Array<string>}
     * @memberof ModelsPersonaCreateRequest
     */
    'locations'?: Array<string>;
    /**
     * A name for describing this persona. Used for easy human-friendly identification.
     * @type {string}
     * @memberof ModelsPersonaCreateRequest
     */
    'persona_name': string;
    /**
     * Optional list of pre-defined persona facet component objects. Each object outlines how a pre-defined persona (\'Car Owners\' or \'International Travelers\') contributes to the persona definition. If left empty, no predefined personas are incorporated into the persona definition. Pre-defined personas have been optimized for financial use cases and have been validated at scale. They can be found by listing personas of facet type \'pre_defined_persona\'. Facet name must be a valid pre-defined persona facet in the persona taxonomy.
     * @type {Array<ModelsFacetWeightObject>}
     * @memberof ModelsPersonaCreateRequest
     */
    'pre_defined_personas'?: Array<ModelsFacetWeightObject>;
}

