/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsAuthResponse
 */
export interface ModelsAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthResponse
     */
    'api_key'?: string;
}

