/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Cashflow details for a given account of a given user
 * @export
 * @interface ModelsAccountCashflowOverview
 */
export interface ModelsAccountCashflowOverview {
    /**
     * Account type
     * @type {string}
     * @memberof ModelsAccountCashflowOverview
     */
    'account_type': string;
    /**
     * Inflow amount on the given window
     * @type {number}
     * @memberof ModelsAccountCashflowOverview
     */
    'inflow_amount': number;
    /**
     * Net cashflow amount on the given window
     * @type {number}
     * @memberof ModelsAccountCashflowOverview
     */
    'net_cashflow_amount': number;
    /**
     * Outflow amount on the given window
     * @type {number}
     * @memberof ModelsAccountCashflowOverview
     */
    'outflow_amount': number;
}

