/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPaginationMetadata } from './models-pagination-metadata';
import { ModelsTransactionEnrichmentResponse } from './models-transaction-enrichment-response';

/**
 * Historic of enriched transactions of a given user
 * @export
 * @interface ModelsUserTransactionsResponse
 */
export interface ModelsUserTransactionsResponse {
    /**
     * List of enriched transactions
     * @type {Array<ModelsTransactionEnrichmentResponse>}
     * @memberof ModelsUserTransactionsResponse
     */
    'enriched_transactions': Array<ModelsTransactionEnrichmentResponse>;
    /**
     * Pagination metadata needed to know the next call
     * @type {ModelsPaginationMetadata}
     * @memberof ModelsUserTransactionsResponse
     */
    'pagination_metadata': ModelsPaginationMetadata;
    /**
     * User identifier
     * @type {string}
     * @memberof ModelsUserTransactionsResponse
     */
    'user_id': string;
}

