/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsTagCategoricalAttributeFilter
 */
export interface ModelsTagCategoricalAttributeFilter {
    /**
     * Allowed values
     * @type {Array<string>}
     * @memberof ModelsTagCategoricalAttributeFilter
     */
    'allowed_values': Array<string>;
    /**
     * Blocked values
     * @type {Array<string>}
     * @memberof ModelsTagCategoricalAttributeFilter
     */
    'blocked_values': Array<string>;
    /**
     * Tag name
     * @type {string}
     * @memberof ModelsTagCategoricalAttributeFilter
     */
    'tag_name': string;
}

