/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsCashflowWindowStatistics } from './models-cashflow-window-statistics';

/**
 * Historic of cashflows for a given user
 * @export
 * @interface ModelsUserCashflowHistoryResponse
 */
export interface ModelsUserCashflowHistoryResponse {
    /**
     * User identifier
     * @type {string}
     * @memberof ModelsUserCashflowHistoryResponse
     */
    'user_id': string;
    /**
     * Windows with calculated flows
     * @type {Array<ModelsCashflowWindowStatistics>}
     * @memberof ModelsUserCashflowHistoryResponse
     */
    'windows': Array<ModelsCashflowWindowStatistics>;
}

