/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsCategoricalAttributeFilter } from './models-categorical-attribute-filter';
import { ModelsNumericalAttributeFilter } from './models-numerical-attribute-filter';
import { ModelsTimestampAttributeFilter } from './models-timestamp-attribute-filter';

/**
 * Extra information for filtering users
 * @export
 * @interface ModelsPostPersonaUsersRequest
 */
export interface ModelsPostPersonaUsersRequest {
    /**
     * Filter birth date based on a date range
     * @type {ModelsTimestampAttributeFilter}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'birth_date'?: ModelsTimestampAttributeFilter;
    /**
     * List of user ids to not be included in the response
     * @type {Array<string>}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'blocklist': Array<string>;
    /**
     * Filter branch based on a list of allowed values
     * @type {ModelsCategoricalAttributeFilter}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'branch': ModelsCategoricalAttributeFilter;
    /**
     * Filter cbo code based on a list of allowed values
     * @type {ModelsCategoricalAttributeFilter}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'cbo_code'?: ModelsCategoricalAttributeFilter;
    /**
     * Filter declared monthly income based on a numeric range
     * @type {ModelsNumericalAttributeFilter}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'declared_monthly_income'?: ModelsNumericalAttributeFilter;
    /**
     * Filter job title based on a list of allowed values
     * @type {ModelsCategoricalAttributeFilter}
     * @memberof ModelsPostPersonaUsersRequest
     */
    'job_title'?: ModelsCategoricalAttributeFilter;
}

