/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsLookalikeLabel
 */
export interface ModelsLookalikeLabel {
    /**
     * Timestamp to filter the features available to the model. Should reflect when the model is called: email sent date, loan initialized date, etc. If None, all user features will be used
     * @type {string}
     * @memberof ModelsLookalikeLabel
     */
    'timestamp'?: string;
    /**
     * UserID is the unique identifier for the user
     * @type {string}
     * @memberof ModelsLookalikeLabel
     */
    'user_id': string;
}

