/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsAutoMLBatchScoresCreateResponse
 */
export interface ModelsAutoMLBatchScoresCreateResponse {
    /**
     * Path where parquet file with the batch scores will be written
     * @type {string}
     * @memberof ModelsAutoMLBatchScoresCreateResponse
     */
    'path': string;
}

