/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsInputLabelSummary } from './models-input-label-summary';

/**
 * 
 * @export
 * @interface ModelsAutoMLLookalikeCreateResponse
 */
export interface ModelsAutoMLLookalikeCreateResponse {
    /**
     * Analysis of input labels detailing amounts of labels given, amounts of labels detected, monthly breakdowns of positive rates and counts, and a breakdown of weights by label value.
     * @type {ModelsInputLabelSummary}
     * @memberof ModelsAutoMLLookalikeCreateResponse
     */
    'input_label_summary': ModelsInputLabelSummary;
    /**
     * Description of the run
     * @type {string}
     * @memberof ModelsAutoMLLookalikeCreateResponse
     */
    'run_description'?: string;
    /**
     * RunID is the unique identifier for the AutoML run
     * @type {string}
     * @memberof ModelsAutoMLLookalikeCreateResponse
     */
    'run_id': string;
}

