/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ModelsPaginationMetadata } from './models-pagination-metadata';
import { ModelsTransactionEnrichmentUser } from './models-transaction-enrichment-user';

/**
 * Page of users of a given module
 * @export
 * @interface ModelsTransactionEnrichmentUsersResponse
 */
export interface ModelsTransactionEnrichmentUsersResponse {
    /**
     * Pagination metadata needed to know the next call
     * @type {ModelsPaginationMetadata}
     * @memberof ModelsTransactionEnrichmentUsersResponse
     */
    'pagination_metadata': ModelsPaginationMetadata;
    /**
     * List of users related to the transactions
     * @type {Array<ModelsTransactionEnrichmentUser>}
     * @memberof ModelsTransactionEnrichmentUsersResponse
     */
    'users': Array<ModelsTransactionEnrichmentUser>;
}

