/*
Hyperplane API Gateway

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelsAuthRequest
 */
export interface ModelsAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthRequest
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthRequest
     */
    'client_secret': string;
}

